# 沿用日常 Mac 的 Oh My Zsh 主题与 Git/fzf 快捷键。
export ZSH=/opt/oh-my-zsh
ZSH_THEME="robbyrussell"
zstyle ':omz:update' mode disabled
plugins=(git fzf zsh-autosuggestions zsh-syntax-highlighting)
source "$ZSH/oh-my-zsh.sh"

HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=50000
setopt HIST_IGNORE_ALL_DUPS HIST_IGNORE_SPACE SHARE_HISTORY
bindkey -e

export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --exclude .git'
eval "$(zoxide init zsh)"

alias ll='eza -lah --group-directories-first'
alias lt='eza --tree --level=2'
alias lg='lazygit'
